ansible

diff --git a/10-install-command b/10-install-command
--- a/10-install-command
+++ b/10-install-command
@@ -9,3 +9,10 @@ else
   echo "you are running with a root access" 
 fi     
 dnf install mysql -y 
+
+if [ $? -eq 0 ]
+then 
+  echo "installing mysql is... SUCCESS"
+else 
+  echo "installing mysql is... FAILURE"
+fi     
