hello world started

diff --git a/20-backup-1 b/20-backup-1
--- a/20-backup-1
+++ b/20-backup-1
@@ -3,82 +3,85 @@
 USERID=$(id -u)
 SOURCE_DIR=$1
 DEST_DIR=$2
-DAYS=${3:-14}
+DAYS=${3:-14} # if DAYS are provided that will be considered, otherwise default 14 days
 
 LOGS_FOLDER="/var/log/shellscript-logs"
 SCRIPT_NAME=$(echo $0 | cut -d "." -f1)
 LOG_FILE="$LOGS_FOLDER/backup.log"
 R="\e[31m"
-G="\e[32"
+G="\e[32m"
 Y="\e[33m"
 N="\e[0m"
 
-mkdir -p $LOGS_FOLDER
-echo "Script started execution at: $(date)" | tee -a $LOG_FILE
-
-if [ $USERID -ne 0 ]
-then 
-   echo -e "$R ERROR:: please run the script with root access $N" | tee -a $LOG_FILE
-   exit 1
-else
-   echo "you are running with root access" | tee -a $LOG_FILE
-fi
-
-# validate function takes as a input as exit status what command that they tried to install
+# validate functions takes input as exit status, what command they tried to install
 VALIDATE(){
     if [ $1 -eq 0 ]
-    then 
-       echo -e "Installing $2 is ... $G SUCCESS $N" | tee -a $LOG_FILE
-    else 
-       echo -e "Installing $2 is ... $R FAILURE $N" | tee -a $LOG_FILE
-       exit 1 
-    fi   
+    then
+        echo -e "$2 is ... $G SUCCESS $N" | tee -a $LOG_FILE
+    else
+        echo -e "$2 is ... $R FAILURE $N" | tee -a $LOG_FILE
+        exit 1
+    fi
 }
 
-usage(){
-    echo "$R USAGE:: $N sh 20-backup-1 <source-directory> <destination-directory> <days(optional)>"
+check_root(){
+    if [ $USERID -ne 0 ]
+    then
+        echo -e "$R ERROR:: Please run this script with root access $N"
+        exit 1 #give other than 0 upto 127
+    else
+        echo "You are running with root access" 
+    fi
 }
 
-if [ $# -lt 0 ]
-then 
-    usage
+check_root
+mkdir -p $LOGS_FOLDER
+
+USAGE(){
+    echo -e "$R USAGE:: $N sh 20-backup.sh <source-dir> <destination-dir> <days(optional)>"
+    exit 1
+}
+
+if [ $# -lt 2 ]
+then
+    USAGE
 fi
 
 if [ ! -d $SOURCE_DIR ]
 then
-    echo -e "$R source directory $SOURCE_DIR does not exist please check $N"
+    echo -e "$R Source Directory $SOURCE_DIR does not exist. Please check $N"
     exit 1
 fi
 
-if [ $# -lt 0 ]
+if [ ! -d $DEST_DIR ]
 then
-    echo -e  "$R destination directory $DEST_DIR does not exist please check $N"
+    echo -e "$R Destination Directory $DEST_DIR does not exist. Please check $N"
     exit 1
-fi 
+fi
 
-FILES=$(find $SOURCE_DIR -name "*.log" -mtime +14)
+FILES=$(find $SOURCE_DIR -name "*.log" -mtime +$DAYS)
+
 if [ ! -z "$FILES" ]
-then 
+then
     echo "Files to zip are: $FILES"
     TIMESTAMP=$(date +%F-%H-%M-%S)
     ZIP_FILE="$DEST_DIR/app-logs-$TIMESTAMP.zip"
     find $SOURCE_DIR -name "*.log" -mtime +$DAYS | zip -@ "$ZIP_FILE"
 
-    
-if [ -f "$ZIP_FILE" ]
- then
-     echo  "successfully created a zip file"   
-    while IFS= read -r filepath
-    do 
-      echo "Deleting file: $filepath"
-        rm -rf $filepath
-    done < $FILES 
-    echo -e "log files found older than $days ... $G SUCCESS $N"
-else 
-    echo -e " zip file creation ... $R FAILURE $N"
-    exit 1
-fi                 
-    
+    if [ -f $ZIP_FILE ]
+    then
+        echo -e "Successfully created Zip file"
+
+        while IFS= read -r filepath
+        do
+            echo "Deleting file: $filepath" | tee -a $LOG_FILE
+            rm -rf $filepath
+        done <<< $FILES
+        echo -e "Log files older than $DAYS from source directory removed ... $G SUCCESS $N"
+    else
+        echo -e "Zip file creation ... $R FAILURE $N"
+        exit 1
+    fi
 else
-    echo -e "no log files found older than $days ... $Y SKIPPING $N" | tee -a $LOG_FILE 
+    echo -e "No log files found older than 14 days ... $Y SKIPPING $N"
 fi         
