hello-world

diff --git a/20-backup-1 b/20-backup-1
--- a/20-backup-1
+++ b/20-backup-1
@@ -55,7 +55,7 @@ then
   exit 1 
 fi 
 
-FILES=$(find $SOURCE_DIR -name "*.log" -mtime +14) | tee -a $LOG_FILE
+FILES=$(find $SOURCE_DIR -name "*.log" -mtime +$days) | tee -a $OG_FILE
 if [ ! -z "$FILES" ] 
 then 
   echo "files to zip are: $FILES" | tee -a $LOG_FILE
@@ -64,19 +64,19 @@ then
   find $SOURCE_DIR -name "*.log" -mtime +14 | zip -@ "$ZIP_FILE" | tee -a $LOG_FILE
 if [ -f "$ZIP_FILE" ]
 then 
-   echo "successfully created a zip file" | tee -a $LOG_FILE
-   while IFS= read -r filepath 
-   do 
-     echo "Deleting file: $filepath"
-     rm -rf $filepath 
-   done < $FILES 
-  echo -e "log files older than 14days found from source directory removed... $G SUCCESS $N" | tee -a $LOG_FILE
-else 
-   echo -e "zip file creation... $R FAILURE $N" | tee -a $LOG_FILE 
-   exit 1
+   echo "successfully created a zip file" | 
+#    while IFS= read -r filepath 
+#    do 
+#      echo "Deleting file: $filepath"
+#      rm -rf $filepath 
+#    done < $FILES 
+#   echo -e "log files older than $days found from source directory removed... $G SUCCESS $N"|tee -a $LOG_FILE
+# else 
+#    echo -e "zip file creation... $R FAILURE $N" | tee -a $LOG_FILE 
+#    exit 1
 fi 
 else 
-  echo -e "no log files found older than 14days... $Y SKIPPING $N" | tee -a $LOG_FILE
+  echo -e "no log files found older than $days... $Y SKIPPING $N" | tee -a $LOG_FILE
 fi 
 END_TIME=$(date +%s)
 TOTAL_TIME=$(( $END_TIME - $START_TIME ))
