hello world started

diff --git a/backup b/backup
--- a/backup
+++ b/backup
@@ -1,8 +1,9 @@
-#!/bin/bash
+#!/bin/nbash
 USERID=$(id -u)
 SOURCE_DIR=$1
 DEST_DIR=$2
 DAYS=${3:-14}
+
 
     R="\e[31m"
     G="\e[32m"
@@ -36,52 +37,49 @@ DAYS=${3:-14}
     }   
 
     usage(){
-        echo -e  "$R USAGE:: $N backup <source-directory> <destination-directory> <days(optional)>"
+        echo -e "$R USAGE:: $N sh backup <source directory> <destination directory> <days(optional)>"
         exit 1
     }
 
     if [ $# -lt 2 ]
     then 
-        usage
+       usage
     fi
 
-if [ ! -d $SOURCE_DIR ]
-then
-   echo -e "$R source directory $SOURCE_DIR does not exist please check $N"
-   exit 1
-fi
+    if [ ! -d $SOURCE_DIR ]
+    then 
+        echo -e "$R source directory $SOURCE_DIR does not exist please check $N"
+        exit 1
+    fi
 
-if [ ! -d $DEST_DIR ]
-then
-   echo -e "$R destination directory $DEST_DIR does not exist please check $N"
-   exit 1
-fi
+    if [ ! -d $DEST_DIR ]
+    then 
+     echo -e "$R destination directory $DEST_DIR does not exist please check $N"
+     exit 1
+   fi
 
-FILES=$(find $SOURCE_DIR -name "*.log" -mtime +14)
-if [ ! -z "$FILES" ]
-then
-   echo "FILES to zip are: $FILES"
-   TIMESTAMP=$(date +%F +%H +%M +%s)
-   ZIP_FILE="$DEST_DIT/app-logs -TIMESTAMP.ZIP"
+   FILES=$(find $SOURCE_DIR -name "*.log" -mtime +14 )
+   if [ ! -z "$FILES" ]
+   then 
+      echo "FILES to zip are : $FILES"
+      TIMESTAMP=$(date +%F +%M +%H +%s)
+      ZIP_FILE="$DEST_DIR/app-logs -TIMESTAMP.zip"
    find $SOURCE_DIR -name "*.log" -mtime +14 | ZIP -@ "$ZIP_FILE"
-if [ -f $ZIP_FILE ]
-then 
-echo "successfully created zip file"
-while IFS= read -r filepath
-do 
-  echo "deleting file : $filepath" | tee -a $LOG_FILE
 
-  rm -rf $filepath
-done <<< $FILES
+   if [ -f $ZIP_FILE ]
+   then 
+      echo "successfully creating a zip file"
 
-   echo -e "log files older than found $days from source directory removed ... $G success $N"
-else
-    echo -e "zip file creation ... $R FAILURE $N"
-fi
+   while IFS=read -r filepath
+   do 
+   echo "deleting file : $filepath"
+    rm -rf $filepath
+   done <<< $FILES  
 
-else 
-   echo -e "no log files found older than 14 days ... $Y SKIPPING $N"
-fi 
-   
-
-   
+     echo -e "log files  older than $days from source directory removed $G success $N"
+  else 
+     echo -e "zip file creation ... $R failure  $N"
+ fi
+   else 
+     echo -e "no log files found older than 14days ... $Y SKIPPING $N" 
+ fi             
