message

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -1,52 +1,46 @@
-#!/bin/bash
-
+#!/bin/bash 
 USERID=$(id -u)
-
 if [ $USERID -ne 0 ]
 then 
    echo "ERROR:: please run this script with root access"
-   exit 1
 else 
-   echo "you are running with root acces"
+   echo "you are running with root access" 
 fi 
 
 # validate function takes input as exit status what command they tried to install 
-VALIDATE(){
-    if [ $1 -eq 0 ]
-    then
-       echo "Installing $2 is ... SUCCESS"
-    else
-       echo "Installing $2 is ... FAILURE"
-       exit1   
-    fi   
-}
-
-dnf list installed mysql 
-if [ $? -ne 0 ]
+if [ $? -eq 0 ]
 then 
-    echo " mysql is not installed ... going to install"
-    dnf install mysql -y
-    VALIDATE $? "MYSQL"
+  echo "Installing $1 is... SUCCESS"
 else 
-    echo "mysql is already installed ... nothing to do"
+  echo "installing $2 is... FAILURE"
 fi 
 
-dnf list installed python3
+dnf list installed mysql -y
 if [ $? -ne 0 ]
 then 
-   echo "python3 is not installed ... going to installed"
-   dnf installed python3 
-   VALIDATE $? "PYTHON3"
-else 
-    echo "python3 is already installed ... nothing to do"
+   echo "mysql is not installed... going to install"
+   dnf install mysql -y 
+   VALIDATE $? "MYSQL" 
+ else 
+   echo "mysql is already installed... nothing to do"
 fi 
 
-dnf list installed nginx
+dnf list installed python3 
 if [ $? -ne 0 ]
-then
-   echo "nginx is not installed ... going to install"
-   dnf install nginx -y 
-   VALIDATE $? "NGINX"
+then 
+  echo "python3 is not installed... going to install"
+  dnf install python3 
+  VALIDATE $? "PYTHON3"
 else 
-   echo "nginx is already installed ... nothing to do"
-fi       
+  echo "python3 is already installed... nothing to do"
+fi 
+
+dnf list installed nginx -y 
+if [ $? -ne 0 ]
+then 
+  echo "nginx is not installed... gong to install"
+  dnf install nginx -y 
+  VALIDATE $? "NGINX" 
+else 
+  echo "nginx is already installed... nothing to do" 
+fi 
