message

diff --git a/install-command b/install-command
--- a/install-command
+++ b/install-command
@@ -3,9 +3,15 @@ USERID=$(id -u)
 if [ $USERID -ne 0 ] 
 then 
    echo "ERROR:: please run this script root access"
+   exit 1
 else 
    echo "you are running with root access"
 fi 
 dnf install mysql -y 
 
-    
+if [ $? -eq 0 ]
+then 
+  echo "installing mysql is... SUCCESS"
+else 
+  echo "installing mysql is... FAILURE" 
+fi
