hello world started

diff --git a/install b/install
--- a/install
+++ b/install
@@ -13,9 +13,10 @@ dnf install mysql -y
 
 if [ $? -eq 0 ]
 then 
-   echo "mysql is not installed...going to install"
+   echo "Installing mysql is...SUCCESS"
 else
-   echo "mysql is already installed...nothing to do"
+   echo "Installing mysql is...FAILURE"
+   #exit 1
 fi 
 
 
