hello world started

diff --git a/install-command b/install-command
--- a/install-command
+++ b/install-command
@@ -9,3 +9,10 @@ else
    echo "you are runnig with root access"
 fi
 dnf install mysql
+
+if [ $? -eq 0 ]
+then
+   echo "Installing mysql is ... SUCCESS"
+else
+   echo "Installing mysql is ... FAILURE"
+fi    
