hello world started

diff --git a/install-command b/install-command
--- a/install-command
+++ b/install-command
@@ -10,3 +10,10 @@ else
   echo "you are running with root access"
 fi
 dnf install mysql -y  
+
+if [ $? -eq 0 ]
+then 
+   echo "installing mysql is: SUCCESS"
+else
+   echo "installing mysql is: FAILURE"
+fi      
