message

diff --git a/logs b/logs
--- a/logs
+++ b/logs
@@ -1,63 +1,62 @@
 #!/bin/bash
-
 USERID=$(id -u)
+
 R="\e[31m"
 G="\e[32m"
 Y="\e[33m"
 N="\e[0m"
+
 LOGS_FOLDER="/var/log/shellscript-logs"
 SCRIPT_NAME=$(echo $0 | cut -d "." -f1)
-LOG_FILE="$LOGS_FOLDER/$SCRIPT_NAME.log"
+LOG_FILE="$LOGS_FOLDER/SCRIPT_NAME.log"
 
-mkdir -p $LOGS_FOLDER
-
-echo -e "Script started executed at: $(date)" | tee -a $LOG_FILE
+mkdir -p $LOGS_FOLDER 
+echo "script executed at: $(date)"&>>$LOG_FILE 
 
 if [ $USERID -ne 0 ]
 then 
-   echo -e "$R ERROR:: please run the script with root access $N" | tee -a $LOG_FILE
+   echo -e "$R ERROR:: please run this script with root access $N" &>>$LOG_FILE
    exit 1
-else
-   echo "you are running root acces" | tee -a $LOG_FILE
-fi
+else 
+   echo "you are running with root access" &>>$LOG_FILE
+fi 
 
-# validate function takes input as exit status what command they tried to install
-VALIDATE(){
-    if [ $1 -eq 0 ]
-    then
-        echo "Installing $2 is ... $G SUCCESS $N" | tee -a $LOG_FILE
+#validate function takes input as exit status what coommand tried to install 
+VALIDATE() {
+    if [ $? -eq 0 ]
+    then 
+       echo -e "installing $1 is... $G SUCCESS $N"
     else
-        echo "Installing $2 is ... $R FAILURE $N" | tee -a $LOG_FILE
-        exit 1
-    fi         
+       echo -e "installing $2 is... $R FAILURE $N"  
+       exit 1
 }
 
-dnf list installed mysql &>>LOG_FILE
+dnf list installed mysql -y &>>$LOG_FILE
 if [ $? -ne 0 ]
-then
-   echo -e "mysql is not installed ... going to install" | tee -a $LOG_FILE
-   dnf install mysql -y &>>LOG_FILE
-   VALIDATE $? "MYSQL"
-else
-    echo -e "mysql is already installed ... $Y nothing to do $N" | tee -a $LOG_FILE
+then 
+  echo "mysql is not installed... going to install" &>>$LOG_FILE
+  dnf install mysql -y &>>$LOG_FILE
+  VALIDATE $? "MYSQL" 
+else 
+  echo -e "nothing to do mysql is... $Y already installed $N" &>>$LOG_FILE
 fi 
 
-dnf list installed nginx &>>LOG_FILE
+dnf list installed python3 &>>$LOG_FILE
 if [ $? -ne 0 ]
-then
-   echo "nginx is not installed ... going to install"
-   dnf install nginx -y &>>LOG_FILE
-   VALIDATE $? "NGINX"
-else
-    echo -e "nginx is already installed ... $Y nothing to do $N" | tee -a $LOG_FILE
+then 
+  echo "python3 is not installed... going to install"
+  dnf install python3 -y &>>$LOG_FILE
+  VALIADTE $? "PYTHON3"
+else 
+  echo -e "nothing to do python3... $Y already installed $N" &>>$LOG_FILE
 fi 
 
-dnf list installed python3 &>>LOG_FILE
-if [ $? -ne 0 ]
-then
-   echo "python3 is not installed ... going to install"
-   dnf install mysql -y &>>LOG_FILE
-   VALIDATE $? "MYSQL"
-else
-    echo -e "python3 is already installed ... $Y nothing to do $N" | tee -a $LOG_FILE
+dnf list installed nginx -y &>>$LOG_FILE
+if [ $? -ne 0 ] 
+then 
+  echo "nginx is not installed... going to install"
+  dnf install nginx -y &>>$LOG_FILE
+  VALIDATE $? "NGINX" 
+else 
+  echo "nothing to do nginx... $Y already installed $N" &>>$LOG_FILE
 fi 
