hello world started

diff --git a/loops b/loops
--- a/loops
+++ b/loops
@@ -1,6 +1,8 @@
-#!/bin/bash
-USERID=$(id -u)
+#!/bin/bash 
 
+#!/bin/bash
+
+USERID=$(id -u)
 R="\e[31m"
 G="\e[32m"
 Y="\e[33m"
@@ -8,39 +10,42 @@ N="\e[0m"
 LOGS_FOLDER="/var/log/shellscript-logs"
 SCRIPT_NAME=$(echo $0 | cut -d "." -f1)
 LOG_FILE="$LOGS_FOLDER/$SCRIPT_NAME.log"
-PACKAGES=("mysql" "nginx" "httpd")
+PACKAGES=("mysql" "nginx" "python3" "httpd")
+
 mkdir -p $LOGS_FOLDER
-echo "script started execution at: $(date)" | tee -a $LOG_FILE
+
+echo -e "Script started executed at: $(date)" | tee -a $LOG_FILE
 
 if [ $USERID -ne 0 ]
 then 
-   echo -e "$R ERROR:: please run this script with root access"
+   echo -e "$R ERROR:: please run the script with root access $N" | tee -a $LOG_FILE
    exit 1
 else
-   echo "you are running with root accesss"
+   echo "you are running root acces" | tee -a $LOG_FILE
 fi
 
-# validate function takes input as exit status what command thay tried to install
+# validate function takes input as exit status what command they tried to install
 VALIDATE(){
     if [ $1 -eq 0 ]
     then
-        echo -e "Installing $2 is ... $G SUCCESS $N"
+        echo "Installing $2 is ... $G SUCCESS $N" | tee -a $LOG_FILE
     else
-        echo -e "Installing $2 is ... $R FAILURE $N"
-        exit 1    
-    fi    
+        echo "Installing $2 is ... $R FAILURE $N" | tee -a $LOG_FILE
+        exit 1
+    fi         
 }
 
-#for package in ${PACKAGES[@]}
-for PACKAGES in $@
-do 
-  dnf list installed $package &>>$LOG_FILE
-  if [ $? -ne 0 ]
-  then 
-     echo -e "package is not installed ... going to installed"
-     dnf install $package &>>$LOG_FILE
-     VALIDATE $? "$PACKAGE"
-  else
-     echo -e "nothing to do $package ... $Y already installed $N"
-  fi
-done     
+for package in  ${PACKAGES[@]}
+do
+
+dnf list installed $PACKAGE
+if [ $? -ne 0 ]
+then 
+   echo -e "$PACKAGE is not installed ... going to install"
+   dnf install $PACKAGE -y 
+   VALIDATE $? "$PACKAGE" 
+else 
+   echo -e "nothing to do $PACKAGE ... $Y already installed $N"
+fi 
+done          
+  
