hello world started

diff --git a/loops b/loops
--- a/loops
+++ b/loops
@@ -1,36 +1,35 @@
 #!/bin/bash
 
-
-#!/bin/bash
-USERID=$(id -u) 
+USERID=$(id -u)
 R="\e[31m"
 G="\e[32m"
 Y="\e[33m"
 N="\e[0m"
-
 LOGS_FOLDER="/var/log/shellscript-logs"
-SCRIPT_NAME=$(echo  $0 | cut -d "." -f1)
+SCRIPT_NAME=$(echo $0 | cut -d "." -f1)
 LOG_FILE="$LOGS_FOLDER/$SCRIPT_NAME.log"
-PACKAGES=("mysql" "python3" "nginx" "httpd")
+PACKAGES=("mysql" "python" "nginx" "httpd")
 
 mkdir -p $LOGS_FOLDER
-echo "script started at: $(date)" |  tee -a $LOG_FILE
+echo "Script started executing at: $(date)" | tee -a $LOG_FILE
+
 if [ $USERID -ne 0 ]
 then
-    echo -e "$R ERROR :: please run this script with root access $N" || tee -a$LOG_FILE
-    exit 1
-else 
-    echo "you are running  with root access" | tee -a $LOG_FILE
-fi   
+    echo -e "$R ERROR:: Please run this script with root access $N" | tee -a $LOG_FILE
+    exit 1 #give other than 0 upto 127
+else
+    echo "You are running with root access" | tee -a $LOG_FILE
+fi
 
+# validate functions takes input as exit status, what command they tried to install
 VALIDATE(){
     if [ $1 -eq 0 ]
-then
-    echo -e "Installing $2 is ..  $G success $N" | tee -a $LOG_FILE
-else 
-    echo  -e "installing $2 is .. $R failure  $N" | tee -a $LOG_FILE
-    exit 1
-fi        
+    then
+        echo -e "Installing $2 is ... $G SUCCESS $N" | tee -a $LOG_FILE
+    else
+        echo -e "Installing $2 is ... $R FAILURE $N" | tee -a $LOG_FILE
+        exit 1
+    fi
 }
 
 #for package in ${PACKAGES[@]}
