hello world started

diff --git a/user b/user
--- a/user
+++ b/user
@@ -1,9 +1,9 @@
 #!/bin/bash
-set -e 
+set -e
 failure(){
-    echo "failed at: $1 $2"
+    echo "failed at :$1 $2"
 }
-trap 'failure "{LINENO}" "${BASH_COMMAND}"' ERR
+trap 'failure "{LINENO}" "{BASH_COMMAND}"' ERR
 
 START_TIME=$(date +%s)
 USERID=$(id -u)
